name: Update README

on:
  schedule:
    - cron: '0 0 * * *' # Atualiza diariamente à meia-noite UTC
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Update README
        run: |
          sed -e "s/\${{ github.actor }}/$(date '+%Y-%m-%d')/" README.md > README.md

      - name: Commit and push if README.md is updated
        run: |
          git config --global user.name 'github-actions[bot]'
          git config --global user.email '41898282+github-actions[bot]@users.noreply.github.com'
          git add README.md
          git commit -m "Update README"
          git push
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
